### ISSUE TITLE
Authentication comptability for Elk client alternative

### ISSUE THREAD

**Issue by edimitchel** [BDX-town/Akkoma#33]
Hi,

As you probably see, a new web client is born which proposes good UI/UX.

I'm trying to connect my account hosted on fr.disroot.org (which is powered by Akkoma).

On login, I'm redirected to https://elk.zone/api/fe.disroot.org/oauth?origin=https://elk.zone
```json
{
	"url": "/api/fe.disroot.org/oauth?origin=https://elk.zone",
	"statusCode": 422,
	"statusMessage": "Missing authentication code.",
	"message": "Missing authentication code.",
	"stack":""
}
```

I'm posting this issue here because I didn't encountering this issue on another Mastodon instance.

Thank you for the effort!

**Comment by Cl0v1s** [comment]
Hi, this repo is the fork used by the Akkoma instance at https://bdx.town

We are not actively developing Akkoma, we can reach them at: https://akkoma.dev/AkkomaGang/akkoma/

**Comment by edimitchel** [comment]
Thank, I'll raise a PR on that repo ;)

**Comment by edimitchel** [comment]
>> https://akkoma.dev/AkkomaGang/akkoma/issues/439

**Comment by Dehelssey** [comment]
for the record it's been discussed on Elk's Discord. Apparently the issue is on their side since they only work with mastodon instances at the moment.

**Comment by edimitchel** [comment]
The issue seems to solved.
